### ISSUE TITLE
Outdated `@stacks/transactions` - Clarity3 SC Deploy Not Supported

### ISSUE THREAD

**Issue by BowTiedBlox** [hirosystems/stacks-functional-tests#23]
### Description

This integration testing environment doesn't support Clarity3 smart contracts. It cannot deploy them as the used `@stacks/transactions` version in this project (version 6.16.0) is outdated and supports only Clarity1 and Clarity2 contract deployments. [Here](https://github.com/hirosystems/stacks-functional-tests/blob/08-01-feat_refresh_functional_test_repo/package.json#L42)) is the specific version.

Clarity3 is supported on `@stacks/transactions` 7.x.x, but upgrading requires significant changes due to numerous updates in this version, including renaming conventions, new methods for handling actions, and other modifications in processing transactions.

Updating `@stacks/network` is likely necessary as well, given its close integration with `@stacks/transactions` and the significant modifications it has undergone.

### How to replicate it

In a test, try deploying a smart contract that includes a call to tenure-height. This will result in a failure with an `abort_by_response` `err none` error.

**Comment by janniks** [comment]
As a quick fix you can use the (int) number `3` for `clarityVersion` in the contract deploy helpers.
I'll update the latest minor version of `6.x.x` to also include the enum.

**Comment by BowTiedBlox** [comment]
It worked with the latest minor version `6.17.0`. That has `Clarity3` on the `clarityVersion` enum. Thank you!
